# Generated by Django 5.1 on 2024-08-25 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llmApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertysummary',
            options={'verbose_name': 'Property Summary', 'verbose_name_plural': 'Property Summaries'},
        ),
    ]
